### ISSUE TITLE
Don't work when used comments in .stylintrc

### ISSUE THREAD

**Issue by carpogoryanin** [dekdekbaloo/atom-stylus-supremacy#5]
Hi, I use [csssr-project-template](https://github.com/CSSSR/csssr-project-template) boilerplate for markup projects. And atom stylus supremacy don't correct `.styl` files relatively those [.stylintrc](https://github.com/CSSSR/csssr-project-template/blob/master/.stylintrc). It works if I delete comments in those config. But can it works with comments like [linter-stylint](https://atom.io/packages/linter-stylint) does?

**Comment by ThisIsManta** [comment]
Hi, I'm the initial developer of **Stylus Supremacy**.

Did you mean Stylus Supremacy could not find or read _.stylintrc_ because of the comments (`//`)?

**Comment by carpogoryanin** [comment]
@ThisIsManta, I suppose it could not read. How I can see you fix it. Waiting for accepting pull request.

**Comment by ThisIsManta** [comment]
Yes, I'm waiting for @dekdekbaloo to merge my pull-request.

**Comment by carpogoryanin** [comment]
@ThisIsManta works great, thanks!
